migration:
    startJavaVersion: 17
    targetJavaVersion: 21
    startingPath:
        - src
    excludePath:
        - target
    metas:
#        - migrateSynchronizedLocker: StampedLock
#        - migrateSynchronizedLocker: ReentrantReadWriteLock
        - junitTagsName: "common"
        - junitTagsExcludePackages:
#        - junitTagsStrategy: add
#        - junitTagsStrategy: skip
#        - junitTagsStrategy: check
        - junitTagsStrategy: replace
        - junitSrcBase: src\test\java
